title: 'BitCamp: Creating a Song Recommendation Engine with Azure'
description: (Add Description Here)
template:
  name: bit-camp-learning-lab
  repo: azure-functions-template
before:
  - type: createPullRequest
    head: bitcamp
    title: 'Week 0: Fundamentals of JavaScript'
    body: prerequisite.md
  - type: updateBranchProtection
steps:
  - title: 'Week 1: Downloading an IDE'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: ide.md
  - title: 'Week 1: Configuring Azure Functions'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: azure.md
  - title: 'Week 1: Learning to Use Github'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: github.md
  - title: 'Week 2: Parsing Multipart Data'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: github.md
  - title: 'Week 2: Creating a Face API Endpoint'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: endpoint.md
  - title: 'Week 2: Calling Face API (Parameters)'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: params.md
  - title: 'Week 2: Calling Face API (Fetch)'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: fetch.md
  - title: 'Week 2: Installing Dependencies'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: dependencies.md
  - title: 'Week 3: Creating an HTML Page'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: html.md
  - title: 'Week 3: Displaying Emotion Data'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: data.md
  - title: 'Week 4: Creating a Web App'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: app.md
  - title: 'Week 4: Making an API Controller'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: apicontroller.md
  - title: 'Week 4: Recommendation Parameters'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: recparams.md
  - title: 'Week 4: Recommendation Call (GET)'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: reccall.md
  - title: 'Week 4: Return Method (API Controller)'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: return.md
  - title: 'Week 4: UI Controller'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: uicontroller.md
  - title: 'Week 4: App Controller'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: appcontroller.md
  - title: 'Week 4: Event Listener (Final Step)'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: eventlistener.md
tags:
  - Azure
  - Spotify API
  - Bit Project
